# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 22:53
from __future__ import unicode_literals

import accounts.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('bio', models.TextField(blank=True, max_length=750, verbose_name='Bio')),
                ('birth_date', models.DateField(blank=True, help_text='YYYY-MM-DD format', null=True, verbose_name='Date of Birth')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('city_town', models.CharField(blank=True, max_length=100, verbose_name='City or Town')),
                ('county_state', models.CharField(blank=True, max_length=100, verbose_name='County or State')),
                ('post_code', models.CharField(blank=True, max_length=20, verbose_name='Post Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('stripe_id', models.CharField(blank=True, default='', max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.AccountUserManager()),
            ],
        ),
    ]
