# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180317_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='some help text for email input', max_length=150, unique=True, verbose_name='email'),
        ),
    ]
