# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180321_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='views'),
        ),
    ]
