# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('product_id', models.IntegerField(default=0, editable=False)),
                ('buyer_id', models.IntegerField(default=0, editable=False)),
                ('seller_id', models.IntegerField(default=0, editable=False)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
