# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
