# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
