# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20180415_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
