# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0003_auto_20180416_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('product_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
