# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20180416_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='product_file',
            field=models.FileField(default='', upload_to=b''),
            preserve_default=False,
        ),
    ]
