# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_purchasehistory_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.IntegerField(),
        ),
    ]
