# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20180416_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='product',
            new_name='product_id',
        ),
    ]
