# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Product Name')),
                ('description', models.TextField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sold_count', models.IntegerField(default=0, editable=False, verbose_name='sold')),
                ('view_count', models.IntegerField(default=0, editable=False, verbose_name='views')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.CharField(choices=[('assets', 'Assets'), ('environment', 'Environment'), ('blueprint', 'Blueprint'), ('materials', 'Materials')], max_length=25)),
                ('ue_version', models.CharField(choices=[(b'4.0', b'4.0'), (b'4.01', b'4.01'), (b'4.02', b'4.02'), (b'4.03', b'4.03'), (b'4.04', b'4.04'), (b'4.05', b'4.05'), (b'4.06', b'4.06'), (b'4.07', b'4.07'), (b'4.08', b'4.08'), (b'4.09', b'4.09'), (b'4.1', b'4.1'), (b'4.11', b'4.11'), (b'4.12', b'4.12'), (b'4.13', b'4.13'), (b'4.14', b'4.14'), (b'4.15', b'4.15'), (b'4.16', b'4.16'), (b'4.17', b'4.17'), (b'4.18', b'4.18'), (b'4.19', b'4.19')], max_length=5, verbose_name='Unreal Engine Version')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product-images')),
                ('file_path', models.CharField(blank=True, max_length=254, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
