# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='sdf', max_length=254),
            preserve_default=False,
        ),
    ]
