# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(default=0, verbose_name='sold'),
        ),
    ]
