# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(default='test', upload_to=products.models.user_directory_path, validators=[products.models.validate_file_extension], verbose_name='Product File'),
            preserve_default=False,
        ),
    ]
