# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180413_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.user_directory_path, validators=[products.models.validate_file_size], verbose_name='Main Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(upload_to=products.models.user_directory_path, validators=[products.models.validate_file_extension, products.models.validate_file_size], verbose_name='Product File'),
        ),
    ]
