# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180329_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='products/%Y-%m/%d/', verbose_name='Product File'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='product-images', verbose_name='Main Product Image'),
        ),
    ]
