# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180330_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-added_date',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='ue_version',
            field=models.CharField(max_length=5, verbose_name='Unreal Engine Version'),
        ),
    ]
