# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180331_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ue_version',
            field=models.CharField(choices=[(b'4.19', b'4.19'), (b'4.18', b'4.18'), (b'4.17', b'4.17'), (b'4.16', b'4.16'), (b'4.15', b'4.15'), (b'4.14', b'4.14'), (b'4.13', b'4.13'), (b'4.12', b'4.12'), (b'4.11', b'4.11'), (b'4.1', b'4.1'), (b'4.09', b'4.09'), (b'4.08', b'4.08'), (b'4.07', b'4.07'), (b'4.06', b'4.06'), (b'4.05', b'4.05'), (b'4.04', b'4.04'), (b'4.03', b'4.03'), (b'4.02', b'4.02'), (b'4.01', b'4.01'), (b'4.0', b'4.0')], default=(b'4.19', b'4.19'), max_length=5, verbose_name='Unreal Engine Version'),
        ),
    ]
