# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='review_text',
        ),
    ]
